print('TABUADA DE UM NÚMERO SÓ')
n = int(input('Escreva um número: '))
print('='*12)
print(f'Tabuada do {n} \n {n}x1 = {n*1} \n {n}x2 = {n*2} \n {n}x3 = {n*3} \n {n}x4 = {n*4} \n {n}x5 = {n*5} \n {n}x6 = {n*6} \n {n}x7 = {n*7} \n {n}x8 = {n*8} \n {n}x9 = {n*9} \n {n}x10 = {n*10}')
print('='*12)